[package]
name = "SimpleProxy"
version = "0.1.0"
authors = ["RootOperator <20143055+RootOperator@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
